### ISSUE TITLE
New platform- camera.combined

### ISSUE THREAD

**Issue by ludeeus** [custom-components/information#2]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
a combination camera feed of the defined cameras.

**Describe alternatives you've considered**
None

**Additional context**
example:
```yaml
camera:
  platform: combined
  entities:
    - camera.camera1
    - camera.camera2
```
